### ISSUE TITLE
Toevoegen nieuwe fusies

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/deelgemeenten#9]
Op 1/1/2025 ontstaan er in Vlaanderen nieuwe gemeenten. Best op tijd de lijsten screenen en aanpassen. Zie https://www.vvsg.be/bestuur/samenwerking-verzelfstandiging/fusies voor alle informatie.

**Comment by koenedaele** [comment]
Ook https://statbel.fgov.be/nl/over-statbel/methodologie/classificaties/geografie

**Comment by koenedaele** [comment]
Interessante discussie:

Deze lijst van deelgemeenten komt met niets overeen, ook niet met de lijst van NIS6 op https://statbel.fgov.be/sites/default/files/Over_Statbel_FR/Nomenclaturen/NIS6nwithnamefrom01012025.xlsx aangezien die zeer vreemde namen hanteert. Het valt wel op dat men in die lijst de oude NIScodes van de deelgemeenten bewaart, maar dan gekoppeld aan een nieuwe NIScode van de gemeente.

Ooit gebruikten wij voor de niscodes van de deelgemeenten codes die lijken op die van statbel. Bij de vorige fusie hebben we voor de nieuwe fusiegemeenten de nieuwe deelgementen bepaald door de oude namen over te nemen, maar hun niscodes aan te passen aan de niscode van de nieuwe gemeente (genre NIS gemeente + volgletter). Statbel heeft een andere aanpak gevolgd. Wat doen wij nu?

1. We werken consequent verder zoals de vorige keer en stellen dus dat de deelgemeenten van de nieuwe gemeenten een nieuwe id krijgen. Borsbeek gaat dus van 11007A naar 11002W (volgende vrije letter binnen Antwerpen). Dat wil zeggen dat we op de meeste plaatsen nog iets van een link met statbel hebben, maar niet voor de vorige fusies en ook niet voor de deelgemeenten die we niet rechtstreeks uit statbel konden halen. Deelgemeenten in onze databanken moeten dan ook hernummerd worden.
2. De deelgemeenten houden hun oude nummer en worden gewoon toegekend aan een nieuwe gemeente. Voordeel hierbij is dat de data in onze toepassingen dezelfde kan blijven. Dit wijkt dan wel af van de vorige keer en dan kan je je de vraag stellen of we de operatie van de vorige keer ongedaan maken. Maar dat moet dan ook wel in alle databanken aangepast worden wat het voordeel dat we niets moeten aanpassen ongedaan maakt.

Zelf dacht ik eerst gewoon voor optie 1 te gaan, maar nu twijfel ik. Meningen van @goessebr , @maarten-vermeyen of anderen?

**Comment by maarten-vermeyen** [comment]
Misschien moeten we de niscodes voor onze deelgemeenten loslaten. Het NIS laat zelf voor lagere niveaus de hierarchische opbouw varen en het lijkt me verwarrend om dan een andere niscode te gebruiken. Als we een eigen identifier(URI) maken, is het duidelijker dat deze conceptueel verschillen. Bovendien hebben we sowieso problemen bij toekomstige fusies als we in antwerpen nu al aan de W zitten. Als we toch voor optie 1 of 2 kiezen, lijkt het me zinnig om voor twee te gaan. Op die wijze is 'oude data' nog steeds makkelijk te combineren.Anders moeten we ergens anders nog een concordantielijst bijhouden voor de oude en de nieuwe codes.

**Comment by goessebr** [comment]
Ik heb er geen uitgesproken mening over. De NIS6 lijst vind ik best verwarrend maar nu snap ik waarom we al aan de letter W zitten bij Antwerpen ondanks slechts 9 districten

Ook hebben we 11 rijen voor 9 districten. Volgens https://nl.wikipedia.org/wiki/Districten_van_Antwerpen horen Zandvliet, Lillo en Berendrecht samen.

Onze lijst:
```
10000	Antwerpen	11002	Antwerpen	11002A	Antwerpen
10000	Antwerpen	11002	Antwerpen	11002B	Lillo
10000	Antwerpen	11002	Antwerpen	11002K	Berendrecht
10000	Antwerpen	11002	Antwerpen	11002L	Zandvliet
10000	Antwerpen	11002	Antwerpen	11002P	Ekeren
10000	Antwerpen	11002	Antwerpen	11002Q	Merksem
10000	Antwerpen	11002	Antwerpen	11002R	Deurne
10000	Antwerpen	11002	Antwerpen	11002S	Borgerhout
10000	Antwerpen	11002	Antwerpen	11002T	Berchem
10000	Antwerpen	11002	Antwerpen	11002U	Wilrijk
10000	Antwerpen	11002	Antwerpen	11002V	Hoboken
```

Ik vind de actuele NIScode als base behouden wel een stuk duidelijkere dan een "oude niscode+letter"-combinatie onder een gemeente met nieuwe niscode. Dus zelfde opmerking als Maarten over de "oude niscode+letter"-combinatie, maar met een andere conclusie want daarom vind ik optie 2 niet zo interessant.

Indien optie 1, zou ik stabel volledig loslaten en ook de gaten opvullen 11002C is dan ons eerst beschikbare ID.

Maar als we toch eigen ID's hebben dan biedt het voorstel van Maarten mogelijk wel meer duidelijkheid, zodat het onmiddellijk duidelijk is dat we een eigen identifier hebben die niets met de identifier van statbel heeft te maken.

Mijn lichte voorkeur:
1. optie 1 met "actuele NISCODE+volgletter" waarbij we statbel loslaten
2. voorstel Maarten waarbij we statbel loslaten
3. statbel volgen

**Comment by koenedaele** [comment]
Ah, deelgemeentes, DE nagel aan mijn doodskist.

Mijn eigen voorkeur zou nog steeds zijn dat er een extern bestand is dat we kunnen volgen, maar als ik naar deze lijst kijk, dan is die nog steeds niet geschikt voor wat wij nodig hebben door dingen zoals:

`11037	Rumst	Rumst	110371	WIJZIGING VAN GEMEENTEGRENS	WIJZIGING VAN GEMEENTEGRENS
`

Onze onderzoekers hebben indertijd inderdaad bewust gekozen om Zandvliet, Lillo en Berendrecht niet als één deelgemeente te behandelen aangezien ze voor een historische benadering van Vlaanderen niet zo relevant zijn.

Mensen zeggen me vaak wel dat er een goeie lijst is, maar ik zie ze in elk geval niet. Misschien moeten we toch eens een project in de markt zetten dat hier eens en voor altijd keuzes in maakt. Maar dat is lange termijn.

Korte termijn kunnen we dus gaan voor één van de twee opties die ik had plus een halve nieuwe voorgesteld door @goessebr en een nieuwe voorgesteld door @maarten-vermeyen :
1. Deelgemeenten hebben als ID de niscode van hun gemeente plus een letter waarbij we verder gaan vanaf de laatste letter.
1bis. Deelgemeenten hebben als ID de niscode van hun gemeente plus een letter waarbij we gaten beginnen opvullen. Nadeel: onze 11002C heeft ooit voor iemand een andere betekenis gehad
2. Deelgemeenten hebben als ID hun oude niscode. Echter, wat als een deelgemeente niet exact overgaat maar in twee gesplitst wordt of zo? Dan moet je in elk geval iets nieuws doen.
3. We maken nieuwe identifiers die in niets lijken op de oude zodat er geen verwarring is. We moeten dan wel een goeie concordantietabel opstellen om onze systemen mee up te daten.

Indien we hier echte LOD van willen maken, moeten we deze data publiceren als RDF en hebben we een URI nodig en moeten we beslissen waar we dat publiceren en met welke extra metadata. Kan misschien als een thesaurus? In een ideale wereld pleit ik nog steeds om dit geografisch af te bakenen zodat je een duidelijke spatial footprint hebt.

Er is trouwens ook nog altijd een interactie met de geografische thema's van het type "deelgemeente" (alhoewel dat onderscheid niet meer bestaat). Waarbij de deelgemeenten vaak een eigen inleiding hadden. Aan de andere kant zitten daar in Knokke-Heist ook dingen bij zoals "Knokke - oude woonkernen" of "Knokke - Albertstrand" wat nooit deelgemeenten geweest zijn.

**Comment by koenedaele** [comment]
Bijkomend probleem bij het omzetten naar LOD is dat er nog steeds geen algemene URI's zijn voor Gemeenten. Er zijn wel URI's voor Gemeentenamen zoals https://data.vlaanderen.be/id/gemeentenaam/44021 die we kunnen gebruiken, maar die zitten in Vlaanderen, niet op Belgisch niveau.

**Comment by goessebr** [comment]
Ik zal voor de gemeentefusies optie 1 uitwerken en een PR aanmaken. Dit wil zeggen de nieuwe niscodes gebruiken en verder gaan op de laatste letter dus geen gaten vullen.

Borsbeek heeft maar 1 deelgemeente (Borsbeek) dus onze letters gaan voorlopig nog niet opraken bij Antwerpen.

Een meer structurele oplossing komt met voorkeur in een apart project later.

**Comment by goessebr** [comment]
Ik ben vastgelopen op Tongeren-Borgloon.

In eerste instantie heb ik de letters overgenomen van de gemeente Tongeren tot 73111V.

Daarna heb ik aangevuld tot Z, daarna heb ik gaten opgevuld (O, I, Q ontbraken, waarschijnlijk omdat ze mogelijk verwarrend zijn met de cijfers 0 en 1). Een mogelijkheid is om als laatste teken ook een cijfer te gebruiken. 731110, 731111, 731112, ... om deze fusie nog net te overleven. Maar ik hoor graag even jullie feedback voor ik verder ga.

```
70000,Limburg,73111,Tongeren-Borgloon,73111A,Tongeren
70000,Limburg,73111,Tongeren-Borgloon,73111B,Koninksem
70000,Limburg,73111,Tongeren-Borgloon,73111C,Neerrepen
70000,Limburg,73111,Tongeren-Borgloon,73111D,Riksingen
70000,Limburg,73111,Tongeren-Borgloon,73111E,Henis
70000,Limburg,73111,Tongeren-Borgloon,73111F,Berg
70000,Limburg,73111,Tongeren-Borgloon,73111G,Mal
70000,Limburg,73111,Tongeren-Borgloon,73111H,Sluizen
70000,Limburg,73111,Tongeren-Borgloon,73111J,Nerem
70000,Limburg,73111,Tongeren-Borgloon,73111K,Vreren
70000,Limburg,73111,Tongeren-Borgloon,73111L,Rutten
70000,Limburg,73111,Tongeren-Borgloon,73111M,Lauw
70000,Limburg,73111,Tongeren-Borgloon,73111N,Widooie
70000,Limburg,73111,Tongeren-Borgloon,73111P,Piringen
70000,Limburg,73111,Tongeren-Borgloon,73111R,Overrepen
70000,Limburg,73111,Tongeren-Borgloon,73111S,'s Herenelderen
70000,Limburg,73111,Tongeren-Borgloon,73111T,Haren
70000,Limburg,73111,Tongeren-Borgloon,73111U,Kolmont
70000,Limburg,73111,Tongeren-Borgloon,73111V,Diets-Heur
70000,Limburg,73111,Tongeren-Borgloon,73111W,Borgloon
70000,Limburg,73111,Tongeren-Borgloon,73111X,Kuttekoven
70000,Limburg,73111,Tongeren-Borgloon,73111Y,Kerniel
70000,Limburg,73111,Tongeren-Borgloon,73111Z,Gors-Opleeuw
70000,Limburg,73111,Tongeren-Borgloon,73111I,Jesseren
70000,Limburg,73111,Tongeren-Borgloon,73111O,Bommershoven
70000,Limburg,73111,Tongeren-Borgloon,73111Q,Groot-Loon
70000,Limburg,73111,Tongeren-Borgloon,PLACEHOLDER,Broekom
70000,Limburg,73111,Tongeren-Borgloon,PLACEHOLDER,Hendrieken
70000,Limburg,73111,Tongeren-Borgloon,PLACEHOLDER,Voort
70000,Limburg,73111,Tongeren-Borgloon,PLACEHOLDER,Gotem
70000,Limburg,73111,Tongeren-Borgloon,PLACEHOLDER,Hoepertingen
70000,Limburg,73111,Tongeren-Borgloon,PLACEHOLDER,Rijkel
```

**Comment by maarten-vermeyen** [comment]
We zijn sowieso screwed lijkt me. Hieronder de NIScodes voor Tongeren van wat zij het niveau 'deelgemeente' noemen:


73111 | Tongeren-Borgloon | Tongeren-Borgloon | 73009A | BORGLOON | BORGLOON
73111 | Tongeren-Borgloon | Tongeren-Borgloon | 73009B | KUTTEKOVEN | KUTTEKOVEN
73111 | Tongeren-Borgloon | Tongeren-Borgloon | 73009C | KERNIEL | KERNIEL
73111 | Tongeren-Borgloon | Tongeren-Borgloon | 73009D | GORS-OPLEEUW | GORS-OPLEEUW
73111 | Tongeren-Borgloon | Tongeren-Borgloon | 73009E | JESSEREN+ DEEL VAN HAREN | JESSEREN+ DEEL VAN HAREN
73111 | Tongeren-Borgloon | Tongeren-Borgloon | 73009F | BOMMERSHOVEN+ DEEL VAN KOLMONT | BOMMERSHOVEN+ DEEL VAN KOLMONT
73111 | Tongeren-Borgloon | Tongeren-Borgloon | 73009G | GROOT-LOON | GROOT-LOON
73111 | Tongeren-Borgloon | Tongeren-Borgloon | 73009H | BROEKOM | BROEKOM
73111 | Tongeren-Borgloon | Tongeren-Borgloon | 73009J | HENDRIEKEN | HENDRIEKEN
73111 | Tongeren-Borgloon | Tongeren-Borgloon | 73009K | VOORT | VOORT
73111 | Tongeren-Borgloon | Tongeren-Borgloon | 73009L | GOTEM | GOTEM
73111 | Tongeren-Borgloon | Tongeren-Borgloon | 73009M | HOEPERTINGEN | HOEPERTINGEN
73111 | Tongeren-Borgloon | Tongeren-Borgloon | 73009N | RIJKEL | RIJKEL

Ik blijf toch voorstander van een ander format dan hetgene het NIS gebruikt. Kan alleen verwarring veroorzaken.

**Comment by goessebr** [comment]
Het probleem is dat als we voor iets nieuws gaan, dat we een heel doordacht iets willen opzetten. En ik werk dit jaar nog 2,5 weken ofzo. En jij ook zoiets? Dus omwille van de tijdsnood zou ik eerder gaan voor iets dat nu lelijk maar werkbaar is, met in het achterhoofd dat we vrij snel na de fusies een nieuw project opzetten puur rond deelgemeentes.

Tenzij jij (of Koen) denkt dit op enkele dagen te kunnen uitklaren.

**Comment by maarten-vermeyen** [comment]
Dan heb ik op zich niets tegen verdergaan met nummers als zesde teken. Merk trouwens op dat spijkerschrift ook nog een optie is als we UTF-8 gebruiken als we over de 10 items geraken: 73111𒀀. ;-)

**Comment by koenedaele** [comment]
Yeey, spijkerschrift!

**Comment by koenedaele** [comment]
Naast de optie om een cijfer te gebruiken, is het denk ik ook mogelijk om een zevende teken te gebruiken (de Excel methode dus). Dan krijg je dingen zoals 73111AA, 73111AB, ... Misschien is het in de inventaris wel geïmplementeerd als een veld met exact 6 tekens, maar dit data bestand maakt in elk geval geen veronderstellingen daarover.

Voor de rest sluit ik me aan bij @goessebr , nu even deze fusieronden overleven en daarna vervangen we die identifiers met iets geheel eigen dat onafhankelijk werkt en kunnen we wel eens kijken om daar URI's van te maken ook.

**Comment by goessebr** [comment]
Het databankveld voor de niscode van een deelgemeente is varchar(10) dus een zevende teken is een optie.

De validatie (openapi in de Inventaris en colander in oe_geoutils) laat eveneens 10 tekens toe

Enkel deze vreemde code in de validator om te kijken of een deelgemeente een correcte bijhorende gemeente heeft meegekregen in https://github.com/OnroerendErfgoed/oe_geoutils/blob/5e7678ca81d93bafa93804662cb91198412efeb0/oe_geoutils/validation/validators_location_elements.py#L43-L53 zal voor problemen zorgen.
Ongedacht of we voor een  cijfer kiezen of voor een zevende teken is deze validator een probleem.

Ik zal voor een zevende teken gaan zodat de schaduw van het spijkerschrift niet boven mijn hoofd hangt. Ik heb https://github.com/OnroerendErfgoed/oe_geoutils/issues/320 om het probleem van hierboven aan te pakken.

**Comment by koenedaele** [comment]
Die validator is zowieso vuil, want dat hecht betekenis aan een identifier die in theorie betekenisloos moet zijn. Die validator moet er dus eigenlijk uit en mag niet gebruikt worden om de hoofdgemeente af te leiden van de deelgemeente.

**Comment by goessebr** [comment]
Fixed via #11
